# state.py — defines the shared state that flows through every agent node

# TypedDict lets us define a dictionary with fixed keys and types
from typing import TypedDict, Annotated
import operator

# BaseMessage is the base class for all LangChain message types
from langchain_core.messages import BaseMessage


# AppState is the single source of truth for our entire pipeline
# Every agent reads from and writes to this state
class AppState(TypedDict):

    # Raw job description text — pasted by user in Chainlit UI
    job_description: str

    # Raw text extracted from uploaded CV file (PDF or DOCX)
    cv_raw_text: str

    # Structured analysis of the JD — extracted by JD Analyzer Agent
    # Contains: role, required skills, responsibilities, tone
    jd_analysis: dict

    # Cover letter draft — written by Cover Letter Agent
    cover_letter_draft: str

    # Cover letter after user reviews and approves at HITL 1
    cover_letter_final: str

    # User feedback at HITL 1 — edit instructions or approval
    hitl_1_feedback: str

    # Interview Q&A list — generated by Interview Prep Agent
    # Each item: {"question": "...", "suggested_answer": "..."}
    interview_qa: list

    # User feedback at HITL 2 — request more, change focus, or accept
    hitl_2_feedback: str

    # Gap report — list of skill mismatches found by QA Agent
    # Each item: {"gap": "...", "advice": "..."}
    qa_flags: list

    # file path of uploaded CV — set by Chainlit before graph runs
    cv_file_path: str

    # final assembled output package — set by assembler node
    final_output: dict

    # Conversation message history — Annotated with operator.add
    # so each agent APPENDS to the list rather than overwriting it
    messages: Annotated[list[BaseMessage], operator.add]